parameters:
  - name: targetEnvironment
    type: string
    default: dev

stages:
  - stage: Apply
    displayName: Apply ${{ parameters.targetEnvironment }}
    dependsOn: Security
    jobs:
      - template: terragrunt-job.yml
        parameters:
          jobName: ApplySelected
          displayName: Apply ${{ parameters.targetEnvironment }}
          azureServiceConnection: sc-azure-iac-${{ parameters.targetEnvironment }}
          deploymentEnvironment: ${{ parameters.targetEnvironment }}
          terragruntCommand: terragrunt run --all --non-interactive --disable-bucket-update -- apply -auto-approve -no-color
          skipDepOutputs: false
